# Use the official PostgreSQL image
FROM postgres:latest

# Set environment variables (You can also use a .env file)
ENV POSTGRES_USER=myuser
ENV POSTGRES_PASSWORD=mypassword
ENV POSTGRES_DB=mydatabase

# Expose PostgreSQL default port
EXPOSE 5432
